/* Språk för Race Point.

   Så fungerar det: engelska är alltid utgångsläget, precis som på FIS egna
   sidor. Väljer besökaren ett annat språk i väljaren uppe till höger kommer
   valet ihåg till nästa besök. Saknas en översättning används engelska.

   Vill du lägga till ett språk: kopiera hela en:{...}-blocket, byt kod och
   översätt värdena. Nycklarna till vänster ska stå kvar oförändrade.
   {x} i en text byts ut mot ett värde när sidan ritas.                      */

window.SPRAK_ORDNING = ['en','sv','de','it','fr','es'];
window.SPRAK_NAMN = {en:'English', sv:'Svenska', de:'Deutsch', it:'Italiano',
                     fr:'Français', es:'Español'};
window.SPRAK_LOCALE = {en:'en-GB', sv:'sv-SE', de:'de-DE', it:'it-IT',
                       fr:'fr-FR', es:'es-ES'};

/* Rutan som föreslår att lägga sidan på hemskärmen. Android och Windows kan
   installera på riktigt med ett klick; iPhone har ingen sådan knapp, där får
   man visa var man trycker i stället. */
window.SPRAK_INSTALL = {
  en:{rubrik:'Add to your home screen', android:'Opens full screen, like an app. No app store, nothing to download.',
      ios:'Tap the share button below, then “Add to Home Screen”.',
      knapp:'Add', senare:'Not now'},
  sv:{rubrik:'Lägg till på hemskärmen', android:'Öppnas i helskärm, som en app. Ingen app-butik, inget att ladda ner.',
      ios:'Tryck på dela-knappen nedanför, välj sedan ”Lägg till på hemskärmen”.',
      knapp:'Lägg till', senare:'Inte nu'},
  de:{rubrik:'Zum Startbildschirm hinzufügen', android:'Öffnet im Vollbild, wie eine App. Kein App Store, kein Download.',
      ios:'Auf das Teilen-Symbol unten tippen, dann „Zum Home-Bildschirm“.',
      knapp:'Hinzufügen', senare:'Später'},
  it:{rubrik:'Aggiungi alla schermata Home', android:'Si apre a schermo intero, come un’app. Nessuno store, niente da scaricare.',
      ios:'Tocca il pulsante di condivisione in basso, poi “Aggiungi a Home”.',
      knapp:'Aggiungi', senare:'Non ora'},
  fr:{rubrik:"Ajouter à l'écran d'accueil", android:"S'ouvre en plein écran, comme une application. Aucun store, rien à télécharger.",
      ios:"Touchez le bouton Partager en bas, puis « Sur l'écran d'accueil ».",
      knapp:'Ajouter', senare:'Plus tard'},
  es:{rubrik:'Añadir a la pantalla de inicio', android:'Se abre a pantalla completa, como una app. Sin tienda, sin descargas.',
      ios:'Toca el botón de compartir abajo y elige “Añadir a inicio”.',
      knapp:'Añadir', senare:'Ahora no'}
};

/* Rubrik över sponsorerna. Medvetet utan varumärkesnamn. */
window.SPRAK_SPONSOR = {
  en:{rubrik:'Powered by'},   sv:{rubrik:'Drivs av'},
  de:{rubrik:'Ermöglicht von'}, it:{rubrik:'Con il sostegno di'},
  fr:{rubrik:'Avec le soutien de'}, es:{rubrik:'Con el apoyo de'}
};

/* Nyhetsrutan. Vi visar rubrik, källa och datum – texten står kvar hos den
   som skrivit den, och läsaren klickar vidare dit. */
window.SPRAK_NYHETER = {
  en:{rubrik:'Alpine news', fot:'Headlines from open feeds. Tap one to read it at the source.'},
  sv:{rubrik:'Alpina nyheter', fot:'Rubriker från öppna flöden. Klicka för att läsa hos källan.'},
  de:{rubrik:'Alpin-Nachrichten', fot:'Schlagzeilen aus offenen Feeds. Zum Lesen auf die Quelle tippen.'},
  it:{rubrik:'Notizie alpine', fot:'Titoli da feed aperti. Tocca per leggere sulla fonte.'},
  fr:{rubrik:'Actualités alpines', fot:'Titres issus de flux ouverts. Touchez pour lire à la source.'},
  es:{rubrik:'Noticias alpinas', fot:'Titulares de fuentes abiertas. Toca para leer en el origen.'}
};

/* Rubriker som delar tävlingslistan i två delar. */
window.SPRAK_AVDELARE = {
  en:{kommande:'Upcoming', tidigare:'Earlier races'},
  sv:{kommande:'Kommande', tidigare:'Tidigare tävlingar'},
  de:{kommande:'Bevorstehend', tidigare:'Frühere Wettkämpfe'},
  it:{kommande:'In programma', tidigare:'Gare precedenti'},
  fr:{kommande:'À venir', tidigare:'Courses précédentes'},
  es:{kommande:'Próximas', tidigare:'Carreras anteriores'}
};

/* Resten av säsongen. Evenemangen kommer ur FIS kalendersidor och har inget
   codex, alltså ingen resultatsida att länka till. De visas som en översikt
   över vad som är på gång, inte som klickbara tävlingar. */
window.SPRAK_SASONG = {
  en:{rubrik:'Rest of the season', antal:'{n} events left this season',
      fot:'Full FIS calendar. Individual races appear above with live timing about a week before the start.'},
  sv:{rubrik:'Resten av säsongen', antal:'{n} evenemang kvar i vinter',
      fot:'Hela FIS-kalendern. De enskilda loppen dyker upp ovanför med livetiming ungefär en vecka före start.'},
  de:{rubrik:'Rest der Saison', antal:'{n} Veranstaltungen in diesem Winter',
      fot:'Der vollständige FIS-Kalender. Einzelne Rennen erscheinen oben mit Livetiming etwa eine Woche vor dem Start.'},
  it:{rubrik:'Resto della stagione', antal:'{n} eventi rimasti quest\'inverno',
      fot:'Calendario FIS completo. Le singole gare compaiono sopra con il live timing circa una settimana prima della partenza.'},
  fr:{rubrik:'Reste de la saison', antal:'{n} événements restants cet hiver',
      fot:'Calendrier FIS complet. Les courses apparaissent ci-dessus avec le chronométrage en direct environ une semaine avant le départ.'},
  es:{rubrik:'Resto de la temporada', antal:'{n} eventos restantes este invierno',
      fot:'Calendario FIS completo. Las carreras aparecen arriba con cronometraje en directo aproximadamente una semana antes de la salida.'}
};

/* Kolumnerna kring poängen, och förklaringen till att ett svagt lopp inte
   försämrar någons poäng. */
window.SPRAK_POANG = {
  en:{fisRace:'Race FIS points', harNu:'Current', battre:'Improvement',
      ingenForsamring:'A weaker race never makes an athlete worse. FIS averages the best results of the season, so only an improvement counts.'},
  sv:{fisRace:'FIS-poäng här', harNu:'Har nu', battre:'Förbättring',
      ingenForsamring:'Ett svagare lopp försämrar aldrig någons poäng. FIS räknar snittet av säsongens bästa resultat, så bara en förbättring räknas.'},
  de:{fisRace:'FIS-Punkte hier', harNu:'Aktuell', battre:'Verbesserung',
      ingenForsamring:'Ein schwächeres Rennen verschlechtert niemanden. FIS mittelt die besten Ergebnisse der Saison, es zählt also nur eine Verbesserung.'},
  it:{fisRace:'Punti FIS gara', harNu:'Attuali', battre:'Miglioramento',
      ingenForsamring:'Una gara più debole non peggiora mai nessuno. La FIS fa la media dei migliori risultati della stagione, quindi conta solo un miglioramento.'},
  fr:{fisRace:'Points FIS course', harNu:'Actuels', battre:'Amélioration',
      ingenForsamring:"Une course plus faible ne dégrade jamais un coureur. La FIS fait la moyenne des meilleurs résultats de la saison, seule une amélioration compte."},
  es:{fisRace:'Puntos FIS carrera', harNu:'Actuales', battre:'Mejora',
      ingenForsamring:'Una carrera más floja nunca empeora a nadie. La FIS promedia los mejores resultados de la temporada, así que solo cuenta una mejora.'}
};

/* Korta tidsenheter till nedräkningen: dygn, timmar, minuter, sekunder. */
window.SPRAK_ENHETER = {
  en:{d:'d', t:'h',   m:'min', s:'s'},
  sv:{d:'d', t:'tim', m:'min', s:'sek'},
  de:{d:'T', t:'Std', m:'Min', s:'Sek'},
  it:{d:'g', t:'h',   m:'min', s:'s'},
  fr:{d:'j', t:'h',   m:'min', s:'s'},
  es:{d:'d', t:'h',   m:'min', s:'s'}
};

window.SPRAK = {

en: {
  ingress:"Choose a race. While it runs, the penalty and the new FIS points are worked out after every finish.",
  alla:"All", herrar:"Men", damer:"Women", allaGrenar:"All events",
  ingaTraffar:"No races match the filter.",
  konM:"men", konW:"women", startKl:"start {t} local time",
  tillbaka:"‹ All races", tillbakaKort:"‹ Back", hamtar:"Loading …",
  idag:"Today", imorgon:"Tomorrow", igar:"Yesterday", live:"LIVE",
  medStodAv:"Supported by",

  tillStart:"until first start", paPlats:"on site", hosDig:"your time",
  pagar:"The race is under way", passerat:"The start time has passed",
  forstaStart:"First start {t} local time",

  penaltyNu:"Penalty right now", tillampad:"applied", beraknad:"calculated",
  iMal:"finished", kvar:"to come",
  last:"The penalty can no longer change.",
  lastForkl:"Nobody still to come has better FIS points than the five that count.",
  rorlig:"The penalty can still move — someone still to come has better FIS points than the fifth one counting now.",
  formel:"Sum A {a} plus sum B {b} minus sum C {c}, divided by ten, plus the category adder {d}. The minimum penalty for {k} is {m}.",
  svagtRubrik:"The penalty is not shown for this race.",
  svagtText:"The points file is missing {x} of {y} starters, which would make the calculation unreliable. Times and positions are still correct.",

  statistik:"Statistics", startande:"starters", fullfoljt:"finished",
  brutit:"did not finish", sekTill:"sec 1st to {n}th", tavlPoangSegrare:"race points, winner",

  resultatSaHarLangt:"Results so far", resultat:"Results",
  nr:"Bib", akare:"Athlete", tid:"Time", diff:"Diff", tavlP:"Race p.",
  nyaFis:"New FIS", nuKol:"Now", vinst:"Gain",
  resultatForkl:"Lower FIS points are better. Green means the athlete improves on this race. Tap a name for the athlete's page.",
  kvarAttAka:"Still to come ({n})", fisPoang:"FIS points", status:"Status", vantar:"waiting",

  vader:"Weather", vind:"Wind", byar:"Gusts", molnighet:"Cloud", luftfuktighet:"Humidity",
  nollgrans:"Freezing level", snodjup:"Snow depth", sikt:"Visibility",
  snoIdag:"Snow today", dygn:"Day", sol:"Sun", kannsSom:"feels like {t}°",
  over10:"over 10", km:"km",
  kurvaForkl:"The curve shows temperature hour by hour for the next day. Blue bars are snowfall, red figures at the top are gusts above 12 m/s. The measuring point is at {h} m — it is colder and windier higher up, and the freezing level tells you where the line runs. Weather from Open-Meteo.",
  ingenStation:"No weather station found for {p}.",

  sandning:"Broadcast and cameras",
  ingenSandning:"No broadcast or camera has been added for this race. FIS does not publish broadcast links in machine-readable form at this level, so organisers add them through the form.",
  sokSandning:"Search YouTube", sokKamera:"Search webcam",
  ejInbaddad:"Some broadcasters do not allow embedding — those open in a new tab.",

  fisPoangRubrik:"FIS points", gren:"Event", poang:"Points", placering:"World ranking",
  nrVarlden:"no. {n}", lankar:"Links", fisBio:"FIS biography",
  tillLive:"Live race points", ingenKlubb:"Club not listed by FIS",
  ingenBio:"No FIS biography", ingetForbund:"National federation not known", sponsorer:"Sponsors",
  ingaEgna:"This athlete has not added social media or sponsors yet. Athletes fill this in themselves, and nothing appears until a person has approved it.",
  laddar:"Loading the athlete's own links …",
  poangForkl:"Lower points are better. The ranking is the athlete's place on the FIS world list for that event.",

  sokPlats:"Search for an athlete by name", sokInga:"No athlete matches that.", sokLaddar:"Searching…",
  dinSidaFraga:"Is this your page?", dinSidaKnapp:"Add your links",
  ejPublicerat:"No results",
  ingenLive:"No live timing for codex {c}.",
  ingenLiveForkl:"Either the race has not opened yet, or FIS has removed the feed — it stays up for about a month afterwards.",
  ingenStartlista:"The feed has no start list yet.",
  okandGren:"Unknown event in the feed: {g}",
  uppdaterad:"updated {t}", oforandrad:"unchanged {t}",
  sprakval:"Language",
  foot:"Race Point is made for the athletes and the athlete community — the people whose season these numbers decide. It is an independent site and is not affiliated with FIS. Points list: {l} (valid {v}). Times and start lists from FIS live timing, points and rankings from the official FIS points list, weather from Open-Meteo. Broadcasts, cameras, social media and sponsors are added by organisers and athletes and shown after approval.",
  grenar:{DH:"Downhill", SL:"Slalom", GS:"Giant slalom", SG:"Super-G", AC:"Combined"}
},

sv: {
  ingress:"Välj tävling. Under tävlingen räknas penalty och nya FIS-poäng fram efter varje målgång.",
  alla:"Alla", herrar:"Herrar", damer:"Damer", allaGrenar:"Alla grenar",
  ingaTraffar:"Inga tävlingar matchar filtret.",
  konM:"herrar", konW:"damer", startKl:"start {t} lokal tid",
  tillbaka:"‹ Alla tävlingar", tillbakaKort:"‹ Tillbaka", hamtar:"Hämtar …",
  idag:"Idag", imorgon:"Imorgon", igar:"Igår", live:"LIVE",
  medStodAv:"Med stöd av",

  tillStart:"till första start", paPlats:"på plats", hosDig:"hos dig",
  pagar:"Tävlingen är igång", passerat:"Starten har passerat",
  forstaStart:"Första start {t} lokal tid",

  penaltyNu:"Penalty just nu", tillampad:"tillämpad", beraknad:"beräknad",
  iMal:"i mål", kvar:"kvar",
  last:"Penalty kan inte ändras mer.",
  lastForkl:"Ingen av dem som är kvar har bättre FIS-poäng än de fem som räknas.",
  rorlig:"Penalty kan fortfarande röra sig — någon som är kvar har bättre FIS-poäng än den femte som räknas nu.",
  formel:"Summa A {a} plus summa B {b} minus summa C {c}, delat med tio, plus kategoritillägg {d}. Minsta penalty för {k} är {m}.",
  svagtRubrik:"Penalty visas inte för den här tävlingen.",
  svagtText:"Poängunderlaget saknar {x} av {y} startande, och då blir uträkningen inte tillförlitlig. Tider och placeringar stämmer ändå.",

  statistik:"Statistik", startande:"startande", fullfoljt:"fullföljt",
  brutit:"brutit", sekTill:"sek 1:a till {n}:a", tavlPoangSegrare:"tävl.poäng segrare",

  resultatSaHarLangt:"Resultat så här långt", resultat:"Resultat",
  nr:"Nr", akare:"Åkare", tid:"Tid", diff:"Diff", tavlP:"Tävl.p",
  nyaFis:"Nya FIS", nuKol:"Nu", vinst:"Vinst",
  resultatForkl:"Lägre FIS-poäng är bättre. Grönt betyder att åkaren förbättrar sina poäng på den här tävlingen. Klicka på ett namn för åkarens sida.",
  kvarAttAka:"Kvar att åka ({n})", fisPoang:"FIS-poäng", status:"Status", vantar:"väntar",

  vader:"Väder", vind:"Vind", byar:"Byar", molnighet:"Molnighet", luftfuktighet:"Luftfuktighet",
  nollgrans:"Nollgradersnivå", snodjup:"Snödjup", sikt:"Sikt",
  snoIdag:"Snö i dag", dygn:"Dygn", sol:"Sol", kannsSom:"känns som {t}°",
  over10:"över 10", km:"km",
  kurvaForkl:"Kurvan visar temperaturen timme för timme det närmaste dygnet. Blå staplar är snöfall, röda siffror överst är vindbyar över 12 m/s. Mätpunkten ligger på {h} m ö.h. — uppe i backen är det kallare och blåsigare, och nollgradersnivån säger var gränsen går. Väderdata från Open-Meteo.",
  ingenStation:"Hittade ingen väderstation för {p}.",

  sandning:"Sändning och kameror",
  ingenSandning:"Ingen sändning eller kamera inlagd för den här tävlingen. FIS publicerar inte sändningslänkar maskinellt på den här nivån, så de fylls i av arrangören via formuläret.",
  sokSandning:"Sök sändning på YouTube", sokKamera:"Sök webbkamera",
  ejInbaddad:"Vissa sändningar tillåter inte att de visas inbäddade — de öppnas i en ny flik.",

  fisPoangRubrik:"FIS-poäng", gren:"Gren", poang:"Poäng", placering:"Placering i världen",
  nrVarlden:"nr {n}", lankar:"Länkar", fisBio:"FIS-biografi",
  tillLive:"Live och poäng", ingenKlubb:"Klubb saknas hos FIS",
  ingenBio:"Ingen FIS-biografi", ingetForbund:"Förbundet okänt", sponsorer:"Sponsorer",
  ingaEgna:"Den här åkaren har inte lagt in sociala medier eller sponsorer än. Åkare fyller i sig själva, och inget syns här förrän en människa godkänt det.",
  laddar:"Laddar åkarens egna länkar …",
  poangForkl:"Lägre poäng är bättre. Placeringen är åkarens plats på FIS världslista i den grenen.",

  sokPlats:"Sök efter en åkare", sokInga:"Ingen åkare matchar.", sokLaddar:"Söker…",
  dinSidaFraga:"Är det här din sida?", dinSidaKnapp:"Lägg till dina länkar",
  ejPublicerat:"Inga resultat",
  ingenLive:"Ingen livetiming för codex {c}.",
  ingenLiveForkl:"Antingen har tävlingen inte öppnats än, eller så har FIS tagit bort flödet — det ligger kvar ungefär en månad efteråt.",
  ingenStartlista:"Flödet innehåller ingen startlista ännu.",
  okandGren:"Okänd gren i flödet: {g}",
  uppdaterad:"uppdaterad {t}", oforandrad:"oförändrad {t}",
  sprakval:"Språk",
  foot:"Race Point är gjord för åkarna och åkarnas krets — de vars säsong de här siffrorna avgör. Sajten är fristående och inte kopplad till FIS. Poängunderlag: {l} (giltig {v}). Tider och startlistor från FIS livetiming, poäng och placeringar från FIS officiella punktlista, väder från Open-Meteo. Sändningar, kameror, sociala medier och sponsorer läggs in av arrangörer och åkare och visas efter godkännande.",
  grenar:{DH:"Störtlopp", SL:"Slalom", GS:"Storslalom", SG:"Super-G", AC:"Kombination"}
},

de: {
  ingress:"Wettkampf wählen. Während des Rennens werden Penalty und neue FIS-Punkte nach jedem Zieleinlauf berechnet.",
  alla:"Alle", herrar:"Herren", damer:"Damen", allaGrenar:"Alle Disziplinen",
  ingaTraffar:"Keine Wettkämpfe entsprechen dem Filter.",
  konM:"Herren", konW:"Damen", startKl:"Start {t} Ortszeit",
  tillbaka:"‹ Alle Wettkämpfe", tillbakaKort:"‹ Zurück", hamtar:"Wird geladen …",
  idag:"Heute", imorgon:"Morgen", igar:"Gestern", live:"LIVE",
  medStodAv:"Unterstützt von",

  tillStart:"bis zum ersten Start", paPlats:"vor Ort", hosDig:"Ihre Zeit",
  pagar:"Das Rennen läuft", passerat:"Die Startzeit ist vorbei",
  forstaStart:"Erster Start {t} Ortszeit",

  penaltyNu:"Penalty aktuell", tillampad:"angewendet", beraknad:"berechnet",
  iMal:"im Ziel", kvar:"ausstehend",
  last:"Der Penalty kann sich nicht mehr ändern.",
  lastForkl:"Niemand von den Ausstehenden hat bessere FIS-Punkte als die fünf, die zählen.",
  rorlig:"Der Penalty kann sich noch ändern — jemand Ausstehendes hat bessere FIS-Punkte als der aktuell fünfte.",
  formel:"Summe A {a} plus Summe B {b} minus Summe C {c}, geteilt durch zehn, plus Kategoriezuschlag {d}. Der Mindest-Penalty für {k} beträgt {m}.",
  svagtRubrik:"Für dieses Rennen wird kein Penalty angezeigt.",
  svagtText:"In der Punkteliste fehlen {x} von {y} Startern, damit wäre die Berechnung nicht verlässlich. Zeiten und Platzierungen stimmen trotzdem.",

  statistik:"Statistik", startande:"Starter", fullfoljt:"im Ziel",
  brutit:"ausgeschieden", sekTill:"Sek. 1. bis {n}.", tavlPoangSegrare:"Rennpunkte Sieger",

  resultatSaHarLangt:"Zwischenstand", resultat:"Ergebnis",
  nr:"Nr.", akare:"Athlet", tid:"Zeit", diff:"Diff.", tavlP:"Rennp.",
  nyaFis:"Neue FIS", nuKol:"Aktuell", vinst:"Gewinn",
  resultatForkl:"Niedrigere FIS-Punkte sind besser. Grün heißt, der Athlet verbessert sich in diesem Rennen. Auf einen Namen tippen für die Athletenseite.",
  kvarAttAka:"Noch am Start ({n})", fisPoang:"FIS-Punkte", status:"Status", vantar:"wartet",

  vader:"Wetter", vind:"Wind", byar:"Böen", molnighet:"Bewölkung", luftfuktighet:"Luftfeuchte",
  nollgrans:"Nullgradgrenze", snodjup:"Schneehöhe", sikt:"Sicht",
  snoIdag:"Schnee heute", dygn:"Tag", sol:"Sonne", kannsSom:"gefühlt {t}°",
  over10:"über 10", km:"km",
  kurvaForkl:"Die Kurve zeigt die Temperatur Stunde für Stunde für den nächsten Tag. Blaue Balken sind Schneefall, rote Zahlen oben sind Böen über 12 m/s. Der Messpunkt liegt auf {h} m — weiter oben ist es kälter und windiger, und die Nullgradgrenze sagt, wo die Grenze verläuft. Wetterdaten von Open-Meteo.",
  ingenStation:"Keine Wetterstation für {p} gefunden.",

  sandning:"Übertragung und Kameras",
  ingenSandning:"Für dieses Rennen ist keine Übertragung und keine Kamera hinterlegt. FIS veröffentlicht auf dieser Ebene keine maschinenlesbaren Links, deshalb tragen die Veranstalter sie über das Formular ein.",
  sokSandning:"Auf YouTube suchen", sokKamera:"Webcam suchen",
  ejInbaddad:"Manche Sender erlauben keine Einbettung — diese öffnen in einem neuen Tab.",

  fisPoangRubrik:"FIS-Punkte", gren:"Disziplin", poang:"Punkte", placering:"Weltranglistenplatz",
  nrVarlden:"Nr. {n}", lankar:"Links", fisBio:"FIS-Biografie",
  tillLive:"Live und Punkte", ingenKlubb:"Verein bei der FIS nicht angegeben",
  ingenBio:"Keine FIS-Biografie", ingetForbund:"Verband unbekannt", sponsorer:"Sponsoren",
  ingaEgna:"Dieser Athlet hat noch keine sozialen Medien oder Sponsoren eingetragen. Athleten tragen sich selbst ein, und nichts erscheint hier, bevor ein Mensch es freigegeben hat.",
  laddar:"Eigene Links werden geladen …",
  poangForkl:"Niedrigere Punkte sind besser. Die Platzierung ist der Rang auf der FIS-Weltliste dieser Disziplin.",

  sokPlats:"Athlet suchen", sokInga:"Kein Athlet passt dazu.", sokLaddar:"Suche…",
  dinSidaFraga:"Ist das deine Seite?", dinSidaKnapp:"Links hinzufügen",
  ejPublicerat:"Keine Ergebnisse",
  ingenLive:"Kein Live-Timing für Codex {c}.",
  ingenLiveForkl:"Entweder ist das Rennen noch nicht geöffnet, oder FIS hat den Feed entfernt — er bleibt etwa einen Monat lang bestehen.",
  ingenStartlista:"Der Feed enthält noch keine Startliste.",
  okandGren:"Unbekannte Disziplin im Feed: {g}",
  uppdaterad:"aktualisiert {t}", oforandrad:"unverändert {t}",
  sprakval:"Sprache",
  foot:"Race Point ist für die Athletinnen und Athleten und ihr Umfeld gemacht — für die, über deren Saison diese Zahlen entscheiden. Die Seite ist unabhängig und steht in keiner Verbindung zur FIS. Punkteliste: {l} (gültig {v}). Zeiten und Startlisten von FIS Live-Timing, Punkte und Platzierungen aus der offiziellen FIS-Punkteliste, Wetter von Open-Meteo. Übertragungen, Kameras, soziale Medien und Sponsoren werden von Veranstaltern und Athleten eingetragen und nach Freigabe angezeigt.",
  grenar:{DH:"Abfahrt", SL:"Slalom", GS:"Riesenslalom", SG:"Super-G", AC:"Kombination"}
},

it: {
  ingress:"Scegli una gara. Durante la gara la penalità e i nuovi punti FIS vengono calcolati dopo ogni arrivo.",
  alla:"Tutte", herrar:"Uomini", damer:"Donne", allaGrenar:"Tutte le specialità",
  ingaTraffar:"Nessuna gara corrisponde al filtro.",
  konM:"uomini", konW:"donne", startKl:"partenza {t} ora locale",
  tillbaka:"‹ Tutte le gare", tillbakaKort:"‹ Indietro", hamtar:"Caricamento …",
  idag:"Oggi", imorgon:"Domani", igar:"Ieri", live:"LIVE",
  medStodAv:"Con il sostegno di",

  tillStart:"alla prima partenza", paPlats:"in loco", hosDig:"ora tua",
  pagar:"La gara è in corso", passerat:"L'ora di partenza è passata",
  forstaStart:"Prima partenza {t} ora locale",

  penaltyNu:"Penalità in questo momento", tillampad:"applicata", beraknad:"calcolata",
  iMal:"arrivati", kvar:"da partire",
  last:"La penalità non può più cambiare.",
  lastForkl:"Nessuno di quelli che devono ancora scendere ha punti FIS migliori dei cinque che contano.",
  rorlig:"La penalità può ancora cambiare — qualcuno che deve scendere ha punti FIS migliori del quinto che conta ora.",
  formel:"Somma A {a} più somma B {b} meno somma C {c}, diviso dieci, più il supplemento di categoria {d}. La penalità minima per {k} è {m}.",
  svagtRubrik:"Per questa gara la penalità non viene mostrata.",
  svagtText:"Mancano {x} atleti su {y} nell'elenco punti, e il calcolo non sarebbe attendibile. Tempi e piazzamenti restano corretti.",

  statistik:"Statistiche", startande:"partenti", fullfoljt:"arrivati",
  brutit:"ritirati", sekTill:"sec dal 1° al {n}°", tavlPoangSegrare:"punti gara vincitore",

  resultatSaHarLangt:"Risultati finora", resultat:"Risultati",
  nr:"Pett.", akare:"Atleta", tid:"Tempo", diff:"Dist.", tavlP:"Punti gara",
  nyaFis:"Nuovi FIS", nuKol:"Ora", vinst:"Guadagno",
  resultatForkl:"Punti FIS più bassi sono migliori. Il verde indica che l'atleta migliora in questa gara. Tocca un nome per la scheda dell'atleta.",
  kvarAttAka:"Ancora da partire ({n})", fisPoang:"Punti FIS", status:"Stato", vantar:"in attesa",

  vader:"Meteo", vind:"Vento", byar:"Raffiche", molnighet:"Nuvolosità", luftfuktighet:"Umidità",
  nollgrans:"Quota zero termico", snodjup:"Neve al suolo", sikt:"Visibilità",
  snoIdag:"Neve oggi", dygn:"Giornata", sol:"Sole", kannsSom:"percepiti {t}°",
  over10:"oltre 10", km:"km",
  kurvaForkl:"La curva mostra la temperatura ora per ora nelle prossime ventiquattr'ore. Le barre blu sono la neve, le cifre rosse in alto sono raffiche sopra 12 m/s. Il punto di misura è a {h} m — più in alto fa più freddo e c'è più vento, e lo zero termico dice dove passa il limite. Dati meteo da Open-Meteo.",
  ingenStation:"Nessuna stazione meteo trovata per {p}.",

  sandning:"Diretta e telecamere",
  ingenSandning:"Per questa gara non è stata inserita nessuna diretta né telecamera. A questo livello la FIS non pubblica i link in forma leggibile da un programma, quindi li inseriscono gli organizzatori tramite il modulo.",
  sokSandning:"Cerca su YouTube", sokKamera:"Cerca webcam",
  ejInbaddad:"Alcune emittenti non consentono l'incorporamento — quelle si aprono in una nuova scheda.",

  fisPoangRubrik:"Punti FIS", gren:"Specialità", poang:"Punti", placering:"Posizione mondiale",
  nrVarlden:"n. {n}", lankar:"Collegamenti", fisBio:"Scheda FIS",
  tillLive:"Live e punti", ingenKlubb:"Club non indicato dalla FIS",
  ingenBio:"Nessuna scheda FIS", ingetForbund:"Federazione sconosciuta", sponsorer:"Sponsor",
  ingaEgna:"Questo atleta non ha ancora inserito social o sponsor. Sono gli atleti stessi a compilare, e nulla appare prima che una persona lo abbia approvato.",
  laddar:"Caricamento dei collegamenti dell'atleta …",
  poangForkl:"Punti più bassi sono migliori. La posizione è quella dell'atleta nella lista mondiale FIS della specialità.",

  sokPlats:"Cerca un atleta", sokInga:"Nessun atleta corrisponde.", sokLaddar:"Ricerca…",
  dinSidaFraga:"È la tua pagina?", dinSidaKnapp:"Aggiungi i tuoi link",
  ejPublicerat:"Nessun risultato",
  ingenLive:"Nessun cronometraggio in diretta per il codex {c}.",
  ingenLiveForkl:"O la gara non è ancora stata aperta, oppure la FIS ha rimosso il flusso — resta disponibile circa un mese.",
  ingenStartlista:"Il flusso non contiene ancora una lista di partenza.",
  okandGren:"Specialità sconosciuta nel flusso: {g}",
  uppdaterad:"aggiornato {t}", oforandrad:"invariato {t}",
  sprakval:"Lingua",
  foot:"Race Point è fatto per gli atleti e la loro comunità — quelli di cui questi numeri decidono la stagione. È un sito indipendente e non affiliato alla FIS. Elenco punti: {l} (valido {v}). Tempi e liste di partenza dal cronometraggio FIS, punti e posizioni dall'elenco punti FIS ufficiale, meteo da Open-Meteo. Dirette, telecamere, social e sponsor sono inseriti da organizzatori e atleti e mostrati dopo approvazione.",
  grenar:{DH:"Discesa libera", SL:"Slalom", GS:"Slalom gigante", SG:"Super-G", AC:"Combinata"}
},

fr: {
  ingress:"Choisissez une course. Pendant la course, la pénalité et les nouveaux points FIS sont calculés après chaque arrivée.",
  alla:"Toutes", herrar:"Hommes", damer:"Femmes", allaGrenar:"Toutes les épreuves",
  ingaTraffar:"Aucune course ne correspond au filtre.",
  konM:"hommes", konW:"femmes", startKl:"départ {t} heure locale",
  tillbaka:"‹ Toutes les courses", tillbakaKort:"‹ Retour", hamtar:"Chargement …",
  idag:"Aujourd'hui", imorgon:"Demain", igar:"Hier", live:"DIRECT",
  medStodAv:"Avec le soutien de",

  tillStart:"avant le premier départ", paPlats:"sur place", hosDig:"votre heure",
  pagar:"La course est en cours", passerat:"L'heure de départ est passée",
  forstaStart:"Premier départ {t} heure locale",

  penaltyNu:"Pénalité actuelle", tillampad:"appliquée", beraknad:"calculée",
  iMal:"à l'arrivée", kvar:"à partir",
  last:"La pénalité ne peut plus changer.",
  lastForkl:"Aucun coureur restant n'a de meilleurs points FIS que les cinq retenus.",
  rorlig:"La pénalité peut encore bouger — un coureur restant a de meilleurs points FIS que le cinquième retenu.",
  formel:"Somme A {a} plus somme B {b} moins somme C {c}, divisé par dix, plus le supplément de catégorie {d}. La pénalité minimale pour {k} est {m}.",
  svagtRubrik:"La pénalité n'est pas affichée pour cette course.",
  svagtText:"Il manque {x} coureurs sur {y} dans la liste de points, le calcul ne serait pas fiable. Les temps et les places restent corrects.",

  statistik:"Statistiques", startande:"partants", fullfoljt:"à l'arrivée",
  brutit:"abandons", sekTill:"sec du 1er au {n}e", tavlPoangSegrare:"points course, vainqueur",

  resultatSaHarLangt:"Résultats provisoires", resultat:"Résultats",
  nr:"Dossard", akare:"Coureur", tid:"Temps", diff:"Écart", tavlP:"Pts course",
  nyaFis:"Nouveaux FIS", nuKol:"Actuel", vinst:"Gain",
  resultatForkl:"Des points FIS plus bas sont meilleurs. Le vert signifie que le coureur s'améliore sur cette course. Touchez un nom pour la fiche du coureur.",
  kvarAttAka:"Encore à partir ({n})", fisPoang:"Points FIS", status:"Statut", vantar:"en attente",

  vader:"Météo", vind:"Vent", byar:"Rafales", molnighet:"Nuages", luftfuktighet:"Humidité",
  nollgrans:"Isotherme zéro", snodjup:"Hauteur de neige", sikt:"Visibilité",
  snoIdag:"Neige aujourd'hui", dygn:"Journée", sol:"Soleil", kannsSom:"ressenti {t}°",
  over10:"plus de 10", km:"km",
  kurvaForkl:"La courbe montre la température heure par heure pour les prochaines vingt-quatre heures. Les barres bleues sont les chutes de neige, les chiffres rouges en haut sont les rafales au-dessus de 12 m/s. Le point de mesure est à {h} m — plus haut il fait plus froid et plus venteux, et l'isotherme zéro indique où passe la limite. Données météo d'Open-Meteo.",
  ingenStation:"Aucune station météo trouvée pour {p}.",

  sandning:"Diffusion et caméras",
  ingenSandning:"Aucune diffusion ni caméra n'a été ajoutée pour cette course. À ce niveau, la FIS ne publie pas de liens exploitables automatiquement, ce sont donc les organisateurs qui les ajoutent via le formulaire.",
  sokSandning:"Chercher sur YouTube", sokKamera:"Chercher une webcam",
  ejInbaddad:"Certains diffuseurs n'autorisent pas l'intégration — ceux-là s'ouvrent dans un nouvel onglet.",

  fisPoangRubrik:"Points FIS", gren:"Épreuve", poang:"Points", placering:"Classement mondial",
  nrVarlden:"n° {n}", lankar:"Liens", fisBio:"Biographie FIS",
  tillLive:"Direct et points", ingenKlubb:"Club non indiqué par la FIS",
  ingenBio:"Pas de biographie FIS", ingetForbund:"Fédération inconnue", sponsorer:"Sponsors",
  ingaEgna:"Ce coureur n'a pas encore ajouté de réseaux sociaux ni de sponsors. Les coureurs remplissent eux-mêmes, et rien n'apparaît avant validation par une personne.",
  laddar:"Chargement des liens du coureur …",
  poangForkl:"Des points plus bas sont meilleurs. Le classement est la place du coureur sur la liste mondiale FIS de l'épreuve.",

  sokPlats:"Rechercher un coureur", sokInga:"Aucun coureur ne correspond.", sokLaddar:"Recherche…",
  dinSidaFraga:"C'est votre page ?", dinSidaKnapp:"Ajouter vos liens",
  ejPublicerat:"Pas de résultats",
  ingenLive:"Pas de chronométrage en direct pour le codex {c}.",
  ingenLiveForkl:"Soit la course n'est pas encore ouverte, soit la FIS a retiré le flux — il reste disponible environ un mois.",
  ingenStartlista:"Le flux ne contient pas encore de liste de départ.",
  okandGren:"Épreuve inconnue dans le flux : {g}",
  uppdaterad:"mis à jour {t}", oforandrad:"inchangé {t}",
  sprakval:"Langue",
  foot:"Race Point est fait pour les coureurs et leur entourage — ceux dont ces chiffres décident la saison. Le site est indépendant et n'est pas affilié à la FIS. Liste de points : {l} (valable {v}). Temps et listes de départ du chronométrage FIS, points et classements de la liste de points officielle FIS, météo d'Open-Meteo. Diffusions, caméras, réseaux sociaux et sponsors sont ajoutés par les organisateurs et les coureurs et affichés après validation.",
  grenar:{DH:"Descente", SL:"Slalom", GS:"Slalom géant", SG:"Super-G", AC:"Combiné"}
},

es: {
  ingress:"Elige una carrera. Durante la carrera, la penalización y los nuevos puntos FIS se calculan tras cada llegada.",
  alla:"Todas", herrar:"Hombres", damer:"Mujeres", allaGrenar:"Todas las disciplinas",
  ingaTraffar:"Ninguna carrera coincide con el filtro.",
  konM:"hombres", konW:"mujeres", startKl:"salida {t} hora local",
  tillbaka:"‹ Todas las carreras", tillbakaKort:"‹ Volver", hamtar:"Cargando …",
  idag:"Hoy", imorgon:"Mañana", igar:"Ayer", live:"EN VIVO",
  medStodAv:"Con el apoyo de",

  tillStart:"para la primera salida", paPlats:"en pista", hosDig:"tu hora",
  pagar:"La carrera está en marcha", passerat:"La hora de salida ya pasó",
  forstaStart:"Primera salida {t} hora local",

  penaltyNu:"Penalización ahora mismo", tillampad:"aplicada", beraknad:"calculada",
  iMal:"en meta", kvar:"por salir",
  last:"La penalización ya no puede cambiar.",
  lastForkl:"Ninguno de los que faltan tiene mejores puntos FIS que los cinco que cuentan.",
  rorlig:"La penalización todavía puede moverse — alguien que falta tiene mejores puntos FIS que el quinto que cuenta ahora.",
  formel:"Suma A {a} más suma B {b} menos suma C {c}, dividido entre diez, más el suplemento de categoría {d}. La penalización mínima para {k} es {m}.",
  svagtRubrik:"La penalización no se muestra en esta carrera.",
  svagtText:"Faltan {x} de {y} corredores en la lista de puntos, y el cálculo no sería fiable. Los tiempos y las posiciones siguen siendo correctos.",

  statistik:"Estadísticas", startande:"salidas", fullfoljt:"llegadas",
  brutit:"abandonos", sekTill:"seg del 1º al {n}º", tavlPoangSegrare:"puntos de carrera, ganador",

  resultatSaHarLangt:"Resultados provisionales", resultat:"Resultados",
  nr:"Dorsal", akare:"Corredor", tid:"Tiempo", diff:"Dif.", tavlP:"Ptos carrera",
  nyaFis:"Nuevos FIS", nuKol:"Actual", vinst:"Ganancia",
  resultatForkl:"Menos puntos FIS es mejor. El verde indica que el corredor mejora en esta carrera. Toca un nombre para ver su ficha.",
  kvarAttAka:"Aún por salir ({n})", fisPoang:"Puntos FIS", status:"Estado", vantar:"esperando",

  vader:"Tiempo", vind:"Viento", byar:"Rachas", molnighet:"Nubosidad", luftfuktighet:"Humedad",
  nollgrans:"Cota de nieve", snodjup:"Espesor de nieve", sikt:"Visibilidad",
  snoIdag:"Nieve hoy", dygn:"Día", sol:"Sol", kannsSom:"sensación {t}°",
  over10:"más de 10", km:"km",
  kurvaForkl:"La curva muestra la temperatura hora a hora durante las próximas veinticuatro horas. Las barras azules son nevadas, las cifras rojas de arriba son rachas por encima de 12 m/s. El punto de medición está a {h} m — más arriba hace más frío y más viento, y la cota de nieve indica dónde está el límite. Datos meteorológicos de Open-Meteo.",
  ingenStation:"No se encontró estación meteorológica para {p}.",

  sandning:"Retransmisión y cámaras",
  ingenSandning:"No se ha añadido retransmisión ni cámara para esta carrera. A este nivel la FIS no publica enlaces legibles por un programa, así que los añaden los organizadores mediante el formulario.",
  sokSandning:"Buscar en YouTube", sokKamera:"Buscar webcam",
  ejInbaddad:"Algunas emisoras no permiten la incrustación — esas se abren en una pestaña nueva.",

  fisPoangRubrik:"Puntos FIS", gren:"Disciplina", poang:"Puntos", placering:"Posición mundial",
  nrVarlden:"nº {n}", lankar:"Enlaces", fisBio:"Ficha FIS",
  tillLive:"En directo y puntos", ingenKlubb:"Club no indicado por la FIS",
  ingenBio:"Sin ficha FIS", ingetForbund:"Federación desconocida", sponsorer:"Patrocinadores",
  ingaEgna:"Este corredor todavía no ha añadido redes sociales ni patrocinadores. Son los propios corredores quienes lo rellenan, y nada aparece hasta que una persona lo ha aprobado.",
  laddar:"Cargando los enlaces del corredor …",
  poangForkl:"Menos puntos es mejor. La posición es el puesto del corredor en la lista mundial FIS de esa disciplina.",

  sokPlats:"Buscar un corredor", sokInga:"Ningún corredor coincide.", sokLaddar:"Buscando…",
  dinSidaFraga:"¿Es tu página?", dinSidaKnapp:"Añade tus enlaces",
  ejPublicerat:"Sin resultados",
  ingenLive:"No hay cronometraje en directo para el codex {c}.",
  ingenLiveForkl:"O la carrera aún no se ha abierto, o la FIS ha retirado el flujo — se mantiene alrededor de un mes.",
  ingenStartlista:"El flujo todavía no contiene lista de salida.",
  okandGren:"Disciplina desconocida en el flujo: {g}",
  uppdaterad:"actualizado {t}", oforandrad:"sin cambios {t}",
  sprakval:"Idioma",
  foot:"Race Point está hecho para los corredores y su comunidad — aquellos cuya temporada deciden estas cifras. Es un sitio independiente y no está afiliado a la FIS. Lista de puntos: {l} (válida {v}). Tiempos y listas de salida del cronometraje FIS, puntos y posiciones de la lista de puntos oficial FIS, meteorología de Open-Meteo. Retransmisiones, cámaras, redes sociales y patrocinadores los añaden organizadores y corredores y se muestran tras su aprobación.",
  grenar:{DH:"Descenso", SL:"Eslalon", GS:"Eslalon gigante", SG:"Súper-G", AC:"Combinada"}
}

};

/* Rutorna på åkarsidan: egna sponsorer, affiliate och kontakt.
   Utmärkningstexten är inte valfri – reklam måste gå att känna igen. */
window.SPRAK_PROFIL = {
  en:{sponsorer:'Sponsors', affiliate:'Equipment and travel',
      affiliateNot:'Advertising. Race Point earns a commission if you buy through these links, and most of it goes to this athlete\u2019s club. You pay exactly the same price.',
      kontakt:'Sponsorship enquiries', kontaktKnapp:'Get in touch',
      kontaktUng:'Enquiries go to the club, which passes them on.',
      kontaktVuxen:'Your message is forwarded. The address is never shown here.'},
  sv:{sponsorer:'Sponsorer', affiliate:'Utrustning och resa',
      affiliateNot:'Reklam. Race Point får provision om du k\u00f6per via l\u00e4nkarna, och st\u00f6rsta delen g\u00e5r till \u00e5karens klubb. Du betalar exakt samma pris.',
      kontakt:'Sponsring', kontaktKnapp:'H\u00f6r av dig',
      kontaktUng:'F\u00f6rfr\u00e5gningar g\u00e5r till klubben, som f\u00f6r dem vidare.',
      kontaktVuxen:'Ditt meddelande vidarebefordras. Adressen visas aldrig h\u00e4r.'},
  de:{sponsorer:'Sponsoren', affiliate:'Ausr\u00fcstung und Reise',
      affiliateNot:'Werbung. Race Point erh\u00e4lt eine Provision, wenn du \u00fcber diese Links kaufst; der gr\u00f6\u00dfte Teil geht an den Verein der Athletin. Du zahlst genau denselben Preis.',
      kontakt:'Sponsoring', kontaktKnapp:'Kontakt aufnehmen',
      kontaktUng:'Anfragen gehen an den Verein, der sie weiterleitet.',
      kontaktVuxen:'Deine Nachricht wird weitergeleitet. Die Adresse wird hier nie gezeigt.'},
  it:{sponsorer:'Sponsor', affiliate:'Attrezzatura e viaggi',
      affiliateNot:'Pubblicit\u00e0. Race Point riceve una commissione se acquisti tramite questi link, e la maggior parte va alla societ\u00e0 dell\u2019atleta. Tu paghi esattamente lo stesso prezzo.',
      kontakt:'Sponsorizzazioni', kontaktKnapp:'Contatta',
      kontaktUng:'Le richieste vanno alla societ\u00e0, che le inoltra.',
      kontaktVuxen:'Il messaggio viene inoltrato. L\u2019indirizzo non appare mai qui.'},
  fr:{sponsorer:'Sponsors', affiliate:'\u00c9quipement et voyage',
      affiliateNot:'Publicit\u00e9. Race Point per\u00e7oit une commission si vous achetez via ces liens, et l\u2019essentiel revient au club du coureur. Vous payez exactement le m\u00eame prix.',
      kontakt:'Partenariats', kontaktKnapp:'Nous contacter',
      kontaktUng:'Les demandes vont au club, qui les transmet.',
      kontaktVuxen:'Votre message est transmis. L\u2019adresse n\u2019appara\u00eet jamais ici.'},
  es:{sponsorer:'Patrocinadores', affiliate:'Equipo y viajes',
      affiliateNot:'Publicidad. Race Point recibe una comisi\u00f3n si compras a trav\u00e9s de estos enlaces, y la mayor parte va al club del corredor. T\u00fa pagas exactamente el mismo precio.',
      kontakt:'Patrocinio', kontaktKnapp:'Ponte en contacto',
      kontaktUng:'Las consultas van al club, que las reenv\u00eda.',
      kontaktVuxen:'Tu mensaje se reenv\u00eda. La direcci\u00f3n nunca se muestra aqu\u00ed.'}
};

/* \u2500\u2500 Formul\u00e4ret d\u00e4r \u00e5karen l\u00e4gger upp sina egna l\u00e4nkar \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
   Sidan lagg-till.html hade all text inbakad p\u00e5 engelska och stod kvar p\u00e5
   engelska \u00e4ven f\u00f6r den som valt tyska. Den l\u00e4ser nu h\u00e4rifr\u00e5n och f\u00f6ljer
   samma spr\u00e5kval som resten av sajten. */
window.SPRAK_FORMULAR = {
  en:{
    titel:'Add your links \u00b7 Race Point',
    h1:'Add your links',
    lead:'Your page on Race Point already exists \u2014 it is built from the official FIS points list. Here you add what is yours: social media, your own site and your sponsors. It costs nothing.',
    varforRubrik:'Why it is worth a quarter of an hour',
    varfor1b:'Your sponsors are seen where people actually look.',
    varfor1:'Your page is found by everyone who searches your name or follows your results. A sponsor logo there is worth more than one in an Instagram story that is gone the next day.',
    varfor2b:'You become searchable as yourself.',
    varfor2:'Today FIS has you as a number and a list of points. Here you exist with your own channels and your own story.',
    varfor3b:'You get your own link to share.',
    varfor3:'If you share it and someone buys something through it, 80 per cent goes to you \u2014 paid to your club and earmarked for you. 10 per cent goes to the Race Point Foundation, which awards grants, and 10 per cent to running the site.',
    varfor4b:'We are negotiating with larger partners.',
    varfor4:'The aim is our own agreements with services ski racers actually use \u2014 currency cards, travel insurance, eSIM \u2014 where you earn when someone signs up through your link.',
    obsB:'Honestly, where this stands:',
    obs:'the links and the sponsors work today. The affiliate programme and the support button are still being built and open during the season. Tick the boxes below and we will let you know when they do \u2014 you are not committing to anything.',
    gruppDu:'Who you are',
    hjalpFis:'Your FIS code is on your page at racepoint.net, and in your FIS biography.',
    fis:'FIS code', namn:'Name', namnPlats:'First name Last name',
    klubb:'Club', klubbPlats:'Your ski club',
    epost:'Your email',
    hjalpEpost:'Used only to contact you about your page, and for occasional Race Point news you can opt out of. Never for advertising, never passed on to anyone else.',
    gruppSocial:'Social media',
    hjalpSocial:'Fill in only what you have. The full address, or just the username.',
    dittNamn:'@yourname',
    webb:'Own website',
    gruppSponsor:'Your sponsors',
    hjalpSponsor:'Name and address. If you have more than three, put them in the last field.',
    sponsor1:'Sponsor 1', sponsor2:'Sponsor 2', sponsor3:'Sponsor 3 and anything else',
    sponsorPlats:'Name \u2013 https://',
    gruppPengar:'Want in when the money side opens?',
    hjalpPengar:'None of this costs anything, and you are not committing. We will contact you before anything is switched on for your page.',
    kryssAffiliate:'Affiliate \u2014 I want my own link and 80 per cent of what it earns, paid to my club.',
    kryssStod:'Support button \u2014 I want to be able to receive gifts towards my season.',
    kryssGuide:'Send me the guide — three ways to fund your season, by email.',
    guideFore:'You can also read it here:', guideLank:'Read the guide',
    fodd:'Year of birth', malsman:'Guardian, if you are under 18',
    malsmanPlats:'Name and email',
    skicka:'Send', skickar:'Sending \u2026', skickat:'Sent',
    villkorB1:'What happens next.',
    villkor1:'We check the links before anything is shown, so that nobody can post something in someone else\u2019s name. It normally takes a day. We publish only links to known services and to real websites \u2014 anything else is removed. If you want something taken down later, just get in touch at the same address.',
    villkorB2:'Your email address.',
    villkor2:'We use it for two things: to contact you if something about your page needs sorting out, and to send the occasional note when Race Point gets new features. You can opt out of the second at any time. The address is never sold or passed on, and it is never shown on your page.',
    felTomB:'Fill in FIS code, name and email.',
    felTom:'We need those three to connect the links to the right person.',
    felIngaB:'You have not filled in any links.',
    felInga:'Add at least one \u2014 otherwise there is nothing to show on your page.',
    tackB:'Thank you \u2014 we have your links.',
    tack:'We will check them and put them on your page, normally within a day. If we have a question we will use the address you gave.',
    felSandB:'That could not be sent right now.',
    felSand:'Check that you are online and try again in a moment.'
  },
  sv:{
    titel:'L\u00e4gg upp dina l\u00e4nkar \u00b7 Race Point',
    h1:'L\u00e4gg upp dina l\u00e4nkar',
    lead:'Din sida p\u00e5 Race Point finns redan \u2014 den byggs ur den officiella FIS-po\u00e4nglistan. H\u00e4r l\u00e4gger du till det som \u00e4r ditt: sociala medier, din egen sajt och dina sponsorer. Det kostar ingenting.',
    varforRubrik:'Varf\u00f6r det \u00e4r v\u00e4rt en kvart',
    varfor1b:'Dina sponsorer syns d\u00e4r folk faktiskt tittar.',
    varfor1:'Din sida hittas av alla som s\u00f6ker p\u00e5 ditt namn eller f\u00f6ljer dina resultat. En sponsorlogga d\u00e4r \u00e4r v\u00e4rd mer \u00e4n en i en Instagramstory som \u00e4r borta dagen efter.',
    varfor2b:'Du blir s\u00f6kbar som dig sj\u00e4lv.',
    varfor2:'I dag har FIS dig som ett nummer och en po\u00e4nglista. H\u00e4r finns du med dina egna kanaler och din egen historia.',
    varfor3b:'Du f\u00e5r en egen l\u00e4nk att dela.',
    varfor3:'Delar du den och n\u00e5gon k\u00f6per n\u00e5got genom den g\u00e5r 80 procent till dig \u2014 utbetalt till din klubb och \u00f6ronm\u00e4rkt f\u00f6r dig. 10 procent g\u00e5r till Race Point Foundation, som delar ut stipendier, och 10 procent till driften av sajten.',
    varfor4b:'Vi f\u00f6rhandlar med st\u00f6rre partner.',
    varfor4:'M\u00e5let \u00e4r egna avtal med tj\u00e4nster som t\u00e4vlings\u00e5kare faktiskt anv\u00e4nder \u2014 valutakort, resef\u00f6rs\u00e4kring, eSIM \u2014 d\u00e4r du tj\u00e4nar n\u00e4r n\u00e5gon skaffar det via din l\u00e4nk.',
    obsB:'\u00c4rligt om l\u00e4get:',
    obs:'l\u00e4nkarna och sponsorerna fungerar i dag. Affiliateprogrammet och st\u00f6dknappen byggs fortfarande och \u00f6ppnar under s\u00e4songen. Kryssa i rutorna nedan s\u00e5 h\u00f6r vi av oss n\u00e4r de g\u00f6r det \u2014 du binder dig inte vid n\u00e5got.',
    gruppDu:'Vem du \u00e4r',
    hjalpFis:'Din FIS-kod st\u00e5r p\u00e5 din sida p\u00e5 racepoint.net, och i din FIS-biografi.',
    fis:'FIS-kod', namn:'Namn', namnPlats:'F\u00f6rnamn Efternamn',
    klubb:'Klubb', klubbPlats:'Din skidklubb',
    epost:'Din e-post',
    hjalpEpost:'Anv\u00e4nds bara f\u00f6r att kontakta dig om din sida, och f\u00f6r enstaka nyheter fr\u00e5n Race Point som du kan tacka nej till. Aldrig f\u00f6r reklam, aldrig vidare till n\u00e5gon annan.',
    gruppSocial:'Sociala medier',
    hjalpSocial:'Fyll bara i det du har. Hela adressen, eller bara anv\u00e4ndarnamnet.',
    dittNamn:'@dittnamn',
    webb:'Egen webbplats',
    gruppSponsor:'Dina sponsorer',
    hjalpSponsor:'Namn och adress. Har du fler \u00e4n tre, skriv dem i sista f\u00e4ltet.',
    sponsor1:'Sponsor 1', sponsor2:'Sponsor 2', sponsor3:'Sponsor 3 och \u00f6vrigt',
    sponsorPlats:'Namn \u2013 https://',
    gruppPengar:'Vill du vara med n\u00e4r pengadelen \u00f6ppnar?',
    hjalpPengar:'Inget av detta kostar n\u00e5got, och du binder dig inte. Vi h\u00f6r av oss innan n\u00e5got sl\u00e5s p\u00e5 f\u00f6r din sida.',
    kryssAffiliate:'Affiliate \u2014 jag vill ha en egen l\u00e4nk och 80 procent av vad den ger, utbetalt till min klubb.',
    kryssStod:'St\u00f6dknapp \u2014 jag vill kunna ta emot g\u00e5vor till min s\u00e4song.',
    kryssGuide:'Skicka mig guiden — tre sätt att få in pengar till din säsong, per e-post.',
    guideFore:'Du kan också läsa den här:', guideLank:'Läs guiden',
    fodd:'F\u00f6delse\u00e5r', malsman:'M\u00e5lsman, om du \u00e4r under 18',
    malsmanPlats:'Namn och e-post',
    skicka:'Skicka', skickar:'Skickar \u2026', skickat:'Skickat',
    villkorB1:'Vad som h\u00e4nder sedan.',
    villkor1:'Vi kontrollerar l\u00e4nkarna innan n\u00e5got visas, s\u00e5 att ingen kan l\u00e4gga upp n\u00e5got i n\u00e5gon annans namn. Det tar normalt en dag. Vi publicerar bara l\u00e4nkar till k\u00e4nda tj\u00e4nster och till riktiga webbplatser \u2014 annat tas bort. Vill du ta bort n\u00e5got senare, h\u00f6r bara av dig till samma adress.',
    villkorB2:'Din e-postadress.',
    villkor2:'Vi anv\u00e4nder den till tv\u00e5 saker: f\u00f6r att kontakta dig om n\u00e5got med din sida beh\u00f6ver redas ut, och f\u00f6r att skicka enstaka rader n\u00e4r Race Point f\u00e5r nya funktioner. Det andra kan du tacka nej till n\u00e4r som helst. Adressen s\u00e4ljs eller l\u00e4mnas aldrig vidare, och den visas aldrig p\u00e5 din sida.',
    felTomB:'Fyll i FIS-kod, namn och e-post.',
    felTom:'Vi beh\u00f6ver de tre f\u00f6r att koppla l\u00e4nkarna till r\u00e4tt person.',
    felIngaB:'Du har inte fyllt i n\u00e5gra l\u00e4nkar.',
    felInga:'L\u00e4gg till minst en \u2014 annars finns det inget att visa p\u00e5 din sida.',
    tackB:'Tack \u2014 vi har dina l\u00e4nkar.',
    tack:'Vi kontrollerar dem och l\u00e4gger upp dem p\u00e5 din sida, normalt inom ett dygn. Har vi en fr\u00e5ga anv\u00e4nder vi adressen du angav.',
    felSandB:'Det gick inte att skicka just nu.',
    felSand:'Kontrollera att du \u00e4r uppkopplad och f\u00f6rs\u00f6k igen om en stund.'
  },
  de:{
    titel:'Deine Links eintragen \u00b7 Race Point',
    h1:'Deine Links eintragen',
    lead:'Deine Seite auf Race Point gibt es bereits \u2014 sie entsteht aus der offiziellen FIS-Punkteliste. Hier tr\u00e4gst du ein, was dir geh\u00f6rt: soziale Medien, deine eigene Website und deine Sponsoren. Es kostet nichts.',
    varforRubrik:'Warum eine Viertelstunde sich lohnt',
    varfor1b:'Deine Sponsoren werden dort gesehen, wo wirklich hingeschaut wird.',
    varfor1:'Deine Seite finden alle, die nach deinem Namen suchen oder deine Ergebnisse verfolgen. Ein Sponsorenlogo dort ist mehr wert als eines in einer Instagram-Story, die am n\u00e4chsten Tag weg ist.',
    varfor2b:'Du wirst als du selbst auffindbar.',
    varfor2:'Heute bist du bei der FIS eine Nummer und eine Punkteliste. Hier existierst du mit deinen eigenen Kan\u00e4len und deiner eigenen Geschichte.',
    varfor3b:'Du bekommst einen eigenen Link zum Teilen.',
    varfor3:'Teilst du ihn und jemand kauft dar\u00fcber etwas, gehen 80 Prozent an dich \u2014 ausgezahlt an deinen Verein und f\u00fcr dich zweckgebunden. 10 Prozent gehen an die Race Point Foundation, die Stipendien vergibt, und 10 Prozent an den Betrieb der Seite.',
    varfor4b:'Wir verhandeln mit gr\u00f6\u00dferen Partnern.',
    varfor4:'Ziel sind eigene Vertr\u00e4ge mit Diensten, die Rennl\u00e4ufer tats\u00e4chlich nutzen \u2014 W\u00e4hrungskarten, Reiseversicherung, eSIM \u2014 bei denen du verdienst, wenn jemand \u00fcber deinen Link abschlie\u00dft.',
    obsB:'Ehrlich zum Stand:',
    obs:'die Links und die Sponsoren funktionieren heute. Das Affiliate-Programm und der Unterst\u00fctzungs-Button werden noch gebaut und \u00f6ffnen im Lauf der Saison. Setz unten die H\u00e4kchen, dann melden wir uns \u2014 du gehst damit keine Verpflichtung ein.',
    gruppDu:'Wer du bist',
    hjalpFis:'Deine FIS-Nummer steht auf deiner Seite auf racepoint.net und in deiner FIS-Biografie.',
    fis:'FIS-Nummer', namn:'Name', namnPlats:'Vorname Nachname',
    klubb:'Verein', klubbPlats:'Dein Skiclub',
    epost:'Deine E-Mail-Adresse',
    hjalpEpost:'Wird nur genutzt, um dich zu deiner Seite zu kontaktieren, und f\u00fcr gelegentliche Race-Point-Neuigkeiten, die du abbestellen kannst. Nie f\u00fcr Werbung, nie an andere weitergegeben.',
    gruppSocial:'Soziale Medien',
    hjalpSocial:'Trag nur ein, was du hast. Die ganze Adresse oder nur den Benutzernamen.',
    dittNamn:'@deinname',
    webb:'Eigene Website',
    gruppSponsor:'Deine Sponsoren',
    hjalpSponsor:'Name und Adresse. Hast du mehr als drei, schreib sie ins letzte Feld.',
    sponsor1:'Sponsor 1', sponsor2:'Sponsor 2', sponsor3:'Sponsor 3 und Weiteres',
    sponsorPlats:'Name \u2013 https://',
    gruppPengar:'Dabei sein, wenn die Geldseite \u00f6ffnet?',
    hjalpPengar:'Nichts davon kostet etwas, und du bindest dich nicht. Wir melden uns, bevor f\u00fcr deine Seite etwas aktiviert wird.',
    kryssAffiliate:'Affiliate \u2014 ich m\u00f6chte einen eigenen Link und 80 Prozent der Einnahmen, ausgezahlt an meinen Verein.',
    kryssStod:'Unterst\u00fctzungs-Button \u2014 ich m\u00f6chte Zuwendungen f\u00fcr meine Saison annehmen k\u00f6nnen.',
    kryssGuide:'Schick mir den Leitfaden — drei Wege, deine Saison zu finanzieren, per E-Mail.',
    guideFore:'Du kannst ihn auch hier lesen:', guideLank:'Leitfaden lesen',
    fodd:'Geburtsjahr', malsman:'Erziehungsberechtigte Person, falls unter 18',
    malsmanPlats:'Name und E-Mail',
    skicka:'Senden', skickar:'Wird gesendet \u2026', skickat:'Gesendet',
    villkorB1:'Wie es weitergeht.',
    villkor1:'Wir pr\u00fcfen die Links, bevor etwas angezeigt wird, damit niemand etwas im Namen einer anderen Person einstellen kann. Das dauert in der Regel einen Tag. Wir ver\u00f6ffentlichen nur Links zu bekannten Diensten und zu echten Websites \u2014 alles andere wird entfernt. Soll sp\u00e4ter etwas verschwinden, melde dich einfach unter derselben Adresse.',
    villkorB2:'Deine E-Mail-Adresse.',
    villkor2:'Wir nutzen sie f\u00fcr zwei Dinge: um dich zu kontaktieren, wenn etwas an deiner Seite gekl\u00e4rt werden muss, und um gelegentlich zu schreiben, wenn Race Point neue Funktionen bekommt. Das Zweite kannst du jederzeit abbestellen. Die Adresse wird nie verkauft oder weitergegeben und nie auf deiner Seite gezeigt.',
    felTomB:'Bitte FIS-Nummer, Name und E-Mail ausf\u00fcllen.',
    felTom:'Diese drei brauchen wir, um die Links der richtigen Person zuzuordnen.',
    felIngaB:'Du hast keine Links eingetragen.',
    felInga:'Trag mindestens einen ein \u2014 sonst gibt es nichts, was auf deiner Seite stehen k\u00f6nnte.',
    tackB:'Danke \u2014 wir haben deine Links.',
    tack:'Wir pr\u00fcfen sie und stellen sie auf deine Seite, in der Regel innerhalb eines Tages. Bei R\u00fcckfragen nutzen wir die angegebene Adresse.',
    felSandB:'Das lie\u00df sich gerade nicht senden.',
    felSand:'Pr\u00fcf deine Verbindung und versuch es gleich noch einmal.'
  },
  it:{
    titel:'Aggiungi i tuoi link \u00b7 Race Point',
    h1:'Aggiungi i tuoi link',
    lead:'La tua pagina su Race Point esiste gi\u00e0 \u2014 nasce dalla lista punti ufficiale FIS. Qui aggiungi ci\u00f2 che \u00e8 tuo: social, il tuo sito e i tuoi sponsor. Non costa nulla.',
    varforRubrik:'Perch\u00e9 vale un quarto d\u2019ora',
    varfor1b:'I tuoi sponsor si vedono dove le persone guardano davvero.',
    varfor1:'La tua pagina la trova chiunque cerchi il tuo nome o segua i tuoi risultati. Un logo l\u00ec vale pi\u00f9 di uno in una storia Instagram che il giorno dopo non c\u2019\u00e8 pi\u00f9.',
    varfor2b:'Diventi ricercabile come te stesso.',
    varfor2:'Oggi per la FIS sei un numero e un elenco di punti. Qui esisti con i tuoi canali e la tua storia.',
    varfor3b:'Ottieni un link tuo da condividere.',
    varfor3:'Se lo condividi e qualcuno acquista tramite il link, l\u201980 per cento va a te \u2014 versato al tuo club e vincolato a te. Il 10 per cento va alla Race Point Foundation, che assegna borse, e il 10 per cento alla gestione del sito.',
    varfor4b:'Stiamo trattando con partner pi\u00f9 grandi.',
    varfor4:'L\u2019obiettivo sono accordi nostri con servizi che gli atleti usano davvero \u2014 carte multivaluta, assicurazioni di viaggio, eSIM \u2014 dove guadagni quando qualcuno si iscrive tramite il tuo link.',
    obsB:'Onestamente, a che punto siamo:',
    obs:'i link e gli sponsor funzionano gi\u00e0 oggi. Il programma affiliate e il pulsante di sostegno sono ancora in costruzione e apriranno durante la stagione. Spunta le caselle qui sotto e ti avviseremo \u2014 non ti stai impegnando a nulla.',
    gruppDu:'Chi sei',
    hjalpFis:'Il tuo codice FIS \u00e8 sulla tua pagina su racepoint.net e nella tua biografia FIS.',
    fis:'Codice FIS', namn:'Nome', namnPlats:'Nome Cognome',
    klubb:'Club', klubbPlats:'Il tuo sci club',
    epost:'La tua email',
    hjalpEpost:'Usata solo per contattarti riguardo alla tua pagina e per qualche notizia da Race Point, a cui puoi rinunciare. Mai per pubblicit\u00e0, mai ceduta ad altri.',
    gruppSocial:'Social',
    hjalpSocial:'Compila solo ci\u00f2 che hai. L\u2019indirizzo completo oppure solo il nome utente.',
    dittNamn:'@iltuonome',
    webb:'Sito personale',
    gruppSponsor:'I tuoi sponsor',
    hjalpSponsor:'Nome e indirizzo. Se ne hai pi\u00f9 di tre, scrivili nell\u2019ultimo campo.',
    sponsor1:'Sponsor 1', sponsor2:'Sponsor 2', sponsor3:'Sponsor 3 e altro',
    sponsorPlats:'Nome \u2013 https://',
    gruppPengar:'Vuoi esserci quando si apre la parte economica?',
    hjalpPengar:'Niente di tutto questo costa, e non ti impegna. Ti contattiamo prima che qualcosa venga attivato sulla tua pagina.',
    kryssAffiliate:'Affiliate \u2014 voglio un link mio e l\u201980 per cento di quel che rende, versato al mio club.',
    kryssStod:'Pulsante di sostegno \u2014 voglio poter ricevere contributi per la mia stagione.',
    kryssGuide:'Mandami la guida — tre modi per finanziare la stagione, via email.',
    guideFore:'Puoi anche leggerla qui:', guideLank:'Leggi la guida',
    fodd:'Anno di nascita', malsman:'Genitore o tutore, se hai meno di 18 anni',
    malsmanPlats:'Nome ed email',
    skicka:'Invia', skickar:'Invio \u2026', skickat:'Inviato',
    villkorB1:'Cosa succede dopo.',
    villkor1:'Controlliamo i link prima di mostrare qualsiasi cosa, cos\u00ec nessuno pu\u00f2 pubblicare a nome di un altro. Di norma serve un giorno. Pubblichiamo solo link a servizi noti e a siti reali \u2014 il resto viene rimosso. Se in seguito vuoi togliere qualcosa, scrivici allo stesso indirizzo.',
    villkorB2:'Il tuo indirizzo email.',
    villkor2:'Lo usiamo per due cose: contattarti se qualcosa sulla tua pagina va sistemato e mandarti due righe quando Race Point ha nuove funzioni. Alla seconda puoi rinunciare quando vuoi. L\u2019indirizzo non viene mai venduto o ceduto, e non compare mai sulla tua pagina.',
    felTomB:'Compila codice FIS, nome ed email.',
    felTom:'Ci servono questi tre dati per collegare i link alla persona giusta.',
    felIngaB:'Non hai inserito nessun link.',
    felInga:'Aggiungine almeno uno \u2014 altrimenti non c\u2019\u00e8 nulla da mostrare sulla tua pagina.',
    tackB:'Grazie \u2014 abbiamo i tuoi link.',
    tack:'Li controlliamo e li mettiamo sulla tua pagina, di norma entro un giorno. Se avremo una domanda useremo l\u2019indirizzo che hai indicato.',
    felSandB:'Non \u00e8 stato possibile inviare adesso.',
    felSand:'Controlla la connessione e riprova tra poco.'
  },
  fr:{
    titel:'Ajoute tes liens \u00b7 Race Point',
    h1:'Ajoute tes liens',
    lead:'Ta page sur Race Point existe d\u00e9j\u00e0 \u2014 elle est construite \u00e0 partir de la liste de points officielle de la FIS. Ici tu ajoutes ce qui est \u00e0 toi : r\u00e9seaux sociaux, ton site et tes sponsors. C\u2019est gratuit.',
    varforRubrik:'Pourquoi cela vaut un quart d\u2019heure',
    varfor1b:'Tes sponsors sont vus l\u00e0 o\u00f9 les gens regardent vraiment.',
    varfor1:'Ta page est trouv\u00e9e par tous ceux qui cherchent ton nom ou suivent tes r\u00e9sultats. Un logo l\u00e0 vaut plus qu\u2019un logo dans une story Instagram disparue le lendemain.',
    varfor2b:'Tu deviens trouvable en tant que toi.',
    varfor2:'Aujourd\u2019hui la FIS te r\u00e9duit \u00e0 un num\u00e9ro et une liste de points. Ici tu existes avec tes propres canaux et ta propre histoire.',
    varfor3b:'Tu obtiens ton propre lien \u00e0 partager.',
    varfor3:'Si tu le partages et que quelqu\u2019un ach\u00e8te via ce lien, 80 pour cent te reviennent \u2014 vers\u00e9s \u00e0 ton club et r\u00e9serv\u00e9s pour toi. 10 pour cent vont \u00e0 la Race Point Foundation, qui attribue des bourses, et 10 pour cent au fonctionnement du site.',
    varfor4b:'Nous n\u00e9gocions avec de plus grands partenaires.',
    varfor4:'L\u2019objectif : nos propres accords avec des services que les coureurs utilisent vraiment \u2014 cartes multidevises, assurance voyage, eSIM \u2014 o\u00f9 tu gagnes quand quelqu\u2019un souscrit via ton lien.',
    obsB:'Honn\u00eatement, o\u00f9 nous en sommes :',
    obs:'les liens et les sponsors fonctionnent d\u00e8s aujourd\u2019hui. Le programme d\u2019affiliation et le bouton de soutien sont encore en construction et ouvriront pendant la saison. Coche les cases ci-dessous et nous te pr\u00e9viendrons \u2014 tu ne t\u2019engages \u00e0 rien.',
    gruppDu:'Qui tu es',
    hjalpFis:'Ton code FIS figure sur ta page sur racepoint.net et dans ta biographie FIS.',
    fis:'Code FIS', namn:'Nom', namnPlats:'Pr\u00e9nom Nom',
    klubb:'Club', klubbPlats:'Ton club de ski',
    epost:'Ton adresse e-mail',
    hjalpEpost:'Utilis\u00e9e uniquement pour te contacter au sujet de ta page et pour quelques nouvelles de Race Point, auxquelles tu peux renoncer. Jamais pour de la publicit\u00e9, jamais transmise \u00e0 qui que ce soit.',
    gruppSocial:'R\u00e9seaux sociaux',
    hjalpSocial:'Ne remplis que ce que tu as. L\u2019adresse compl\u00e8te ou simplement le nom d\u2019utilisateur.',
    dittNamn:'@tonnom',
    webb:'Site personnel',
    gruppSponsor:'Tes sponsors',
    hjalpSponsor:'Nom et adresse. Si tu en as plus de trois, mets-les dans le dernier champ.',
    sponsor1:'Sponsor 1', sponsor2:'Sponsor 2', sponsor3:'Sponsor 3 et le reste',
    sponsorPlats:'Nom \u2013 https://',
    gruppPengar:'Tu veux en \u00eatre quand la partie financi\u00e8re ouvrira ?',
    hjalpPengar:'Rien de tout cela ne co\u00fbte quoi que ce soit et ne t\u2019engage. Nous te contacterons avant d\u2019activer quoi que ce soit sur ta page.',
    kryssAffiliate:'Affiliation \u2014 je veux mon propre lien et 80 pour cent de ce qu\u2019il rapporte, vers\u00e9s \u00e0 mon club.',
    kryssStod:'Bouton de soutien \u2014 je veux pouvoir recevoir des dons pour ma saison.',
    kryssGuide:'Envoyez-moi le guide — trois façons de financer ta saison, par e-mail.',
    guideFore:'Tu peux aussi le lire ici :', guideLank:'Lire le guide',
    fodd:'Ann\u00e9e de naissance', malsman:'Responsable l\u00e9gal, si tu as moins de 18 ans',
    malsmanPlats:'Nom et e-mail',
    skicka:'Envoyer', skickar:'Envoi \u2026', skickat:'Envoy\u00e9',
    villkorB1:'Ce qui se passe ensuite.',
    villkor1:'Nous v\u00e9rifions les liens avant d\u2019afficher quoi que ce soit, pour que personne ne puisse publier au nom d\u2019un autre. Cela prend normalement un jour. Nous ne publions que des liens vers des services connus et des sites r\u00e9els \u2014 le reste est retir\u00e9. Si tu veux retirer quelque chose plus tard, \u00e9cris-nous \u00e0 la m\u00eame adresse.',
    villkorB2:'Ton adresse e-mail.',
    villkor2:'Nous l\u2019utilisons pour deux choses : te contacter si quelque chose sur ta page doit \u00eatre r\u00e9gl\u00e9, et t\u2019\u00e9crire de temps en temps quand Race Point ajoute des fonctions. Tu peux renoncer \u00e0 la seconde \u00e0 tout moment. L\u2019adresse n\u2019est jamais vendue ni transmise, et n\u2019appara\u00eet jamais sur ta page.',
    felTomB:'Remplis le code FIS, le nom et l\u2019e-mail.',
    felTom:'Ces trois \u00e9l\u00e9ments nous sont n\u00e9cessaires pour relier les liens \u00e0 la bonne personne.',
    felIngaB:'Tu n\u2019as rempli aucun lien.',
    felInga:'Ajoutes-en au moins un \u2014 sinon il n\u2019y a rien \u00e0 montrer sur ta page.',
    tackB:'Merci \u2014 nous avons tes liens.',
    tack:'Nous les v\u00e9rifions et les mettons sur ta page, normalement sous un jour. En cas de question, nous utiliserons l\u2019adresse que tu as indiqu\u00e9e.',
    felSandB:'L\u2019envoi n\u2019a pas pu se faire \u00e0 l\u2019instant.',
    felSand:'V\u00e9rifie ta connexion et r\u00e9essaie dans un moment.'
  },
  es:{
    titel:'A\u00f1ade tus enlaces \u00b7 Race Point',
    h1:'A\u00f1ade tus enlaces',
    lead:'Tu p\u00e1gina en Race Point ya existe \u2014 se construye con la lista de puntos oficial de la FIS. Aqu\u00ed a\u00f1ades lo que es tuyo: redes sociales, tu propio sitio y tus patrocinadores. No cuesta nada.',
    varforRubrik:'Por qu\u00e9 merece un cuarto de hora',
    varfor1b:'Tus patrocinadores se ven donde la gente mira de verdad.',
    varfor1:'Tu p\u00e1gina la encuentra cualquiera que busque tu nombre o siga tus resultados. Un logotipo ah\u00ed vale m\u00e1s que uno en una historia de Instagram que desaparece al d\u00eda siguiente.',
    varfor2b:'Pasas a ser localizable como t\u00fa mismo.',
    varfor2:'Hoy la FIS te tiene como un n\u00famero y una lista de puntos. Aqu\u00ed existes con tus propios canales y tu propia historia.',
    varfor3b:'Consigues tu propio enlace para compartir.',
    varfor3:'Si lo compartes y alguien compra a trav\u00e9s de \u00e9l, el 80 por ciento va para ti \u2014 abonado a tu club y reservado para ti. El 10 por ciento va a la Race Point Foundation, que concede becas, y el 10 por ciento al funcionamiento del sitio.',
    varfor4b:'Estamos negociando con socios m\u00e1s grandes.',
    varfor4:'El objetivo son acuerdos propios con servicios que los corredores usan de verdad \u2014 tarjetas multidivisa, seguro de viaje, eSIM \u2014 donde ganas cuando alguien se da de alta con tu enlace.',
    obsB:'Con franqueza, d\u00f3nde estamos:',
    obs:'los enlaces y los patrocinadores funcionan hoy. El programa de afiliaci\u00f3n y el bot\u00f3n de apoyo se est\u00e1n construyendo y abrir\u00e1n durante la temporada. Marca las casillas de abajo y te avisaremos \u2014 no te comprometes a nada.',
    gruppDu:'Qui\u00e9n eres',
    hjalpFis:'Tu c\u00f3digo FIS est\u00e1 en tu p\u00e1gina en racepoint.net y en tu biograf\u00eda FIS.',
    fis:'C\u00f3digo FIS', namn:'Nombre', namnPlats:'Nombre y apellidos',
    klubb:'Club', klubbPlats:'Tu club de esqu\u00ed',
    epost:'Tu correo electr\u00f3nico',
    hjalpEpost:'Solo se usa para contactarte sobre tu p\u00e1gina y para alguna novedad de Race Point, que puedes rechazar. Nunca para publicidad, nunca se cede a nadie.',
    gruppSocial:'Redes sociales',
    hjalpSocial:'Rellena solo lo que tengas. La direcci\u00f3n completa o solo el nombre de usuario.',
    dittNamn:'@tunombre',
    webb:'Sitio propio',
    gruppSponsor:'Tus patrocinadores',
    hjalpSponsor:'Nombre y direcci\u00f3n. Si tienes m\u00e1s de tres, escr\u00edbelos en el \u00faltimo campo.',
    sponsor1:'Patrocinador 1', sponsor2:'Patrocinador 2', sponsor3:'Patrocinador 3 y dem\u00e1s',
    sponsorPlats:'Nombre \u2013 https://',
    gruppPengar:'\u00bfQuieres estar cuando se abra la parte econ\u00f3mica?',
    hjalpPengar:'Nada de esto cuesta nada ni te compromete. Te contactaremos antes de activar algo en tu p\u00e1gina.',
    kryssAffiliate:'Afiliaci\u00f3n \u2014 quiero mi propio enlace y el 80 por ciento de lo que genere, abonado a mi club.',
    kryssStod:'Bot\u00f3n de apoyo \u2014 quiero poder recibir aportaciones para mi temporada.',
    kryssGuide:'Envíame la guía — tres formas de financiar tu temporada, por correo.',
    guideFore:'También puedes leerla aquí:', guideLank:'Leer la guía',
    fodd:'A\u00f1o de nacimiento', malsman:'Tutor legal, si eres menor de 18',
    malsmanPlats:'Nombre y correo',
    skicka:'Enviar', skickar:'Enviando \u2026', skickat:'Enviado',
    villkorB1:'Qu\u00e9 pasa despu\u00e9s.',
    villkor1:'Revisamos los enlaces antes de mostrar nada, para que nadie pueda publicar en nombre de otra persona. Suele llevar un d\u00eda. Solo publicamos enlaces a servicios conocidos y a sitios reales \u2014 lo dem\u00e1s se retira. Si m\u00e1s adelante quieres quitar algo, escr\u00edbenos a la misma direcci\u00f3n.',
    villkorB2:'Tu direcci\u00f3n de correo.',
    villkor2:'La usamos para dos cosas: contactarte si algo de tu p\u00e1gina hay que resolver, y escribirte de vez en cuando cuando Race Point tiene funciones nuevas. Lo segundo puedes rechazarlo cuando quieras. La direcci\u00f3n nunca se vende ni se cede, y nunca se muestra en tu p\u00e1gina.',
    felTomB:'Rellena el c\u00f3digo FIS, el nombre y el correo.',
    felTom:'Necesitamos esos tres datos para vincular los enlaces a la persona correcta.',
    felIngaB:'No has rellenado ning\u00fan enlace.',
    felInga:'A\u00f1ade al menos uno \u2014 si no, no hay nada que mostrar en tu p\u00e1gina.',
    tackB:'Gracias \u2014 tenemos tus enlaces.',
    tack:'Los revisamos y los ponemos en tu p\u00e1gina, normalmente en un d\u00eda. Si tenemos alguna duda usaremos la direcci\u00f3n que has indicado.',
    felSandB:'No se ha podido enviar ahora mismo.',
    felSand:'Comprueba que tienes conexi\u00f3n y vuelve a intentarlo en un momento.'
  }
};
